'use client';
import { useState } from 'react';
import { ArrowUpRight, MapPin, UserRound, Flag, FileText, Download, CalendarDays } from 'lucide-react';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { FacebookFeed } from './facebook-feed';
import { Shell, PageHeading, SectionHeading, FACEBOOK } from './site';
import clubsData from '@/data/clubs.json';
import boardData from '@/data/board.json';
import calendarData from '@/data/calendar.json';
import documentData from '@/data/documents.generated.json';

function DemoNotice(){ return <div className="notice"><span className="notice-label">PËRMBAJTJE DEMONSTRUESE</span><p>Emrat dhe të dhënat më poshtë janë shembuj. Lista zyrtare do të publikohet së shpejti.</p></div>; }
export function BoardPage(){return <Shell active="Bordi"><PageHeading section="FEDERATA" title="Bordi i federatës" text="Njerëzit që udhëheqin dhe mbështesin zhvillimin e auto sportit në Kosovë."/><section className="container section">{boardData.isDemo && <DemoNotice/>}<div className="board-intro"><div><div className="eyebrow"><span/> UDHËHEQJA</div><h2>Bashkë, për<br/>sportin tonë.</h2><p>Njihuni me kryetarin, nënkryetarët dhe anëtarët e bordit të federatës.</p></div><figure><img src="/images/assembly.jpg" alt="Takim i Kuvendit të Punës së FASK-ut"/><figcaption>Kuvendi i Punës i FASK-ut · Foto: <a href="https://autoportali.com/fask-mbajti-kuvendin-e-punes-2/" target="_blank" rel="noreferrer">Autoportali</a></figcaption></figure></div><div className="board-grid">{boardData.members.map((person,i)=><article className={'member-card '+(i===0?'president':'')} key={person.id}><div className="member-visual">{person.photo?<img src={person.photo} alt={person.name} loading="lazy"/>:<UserRound size={60} strokeWidth={1}/>}<span className="member-number">{String(i+1).padStart(2,'0')}</span></div><div className="member-copy"><span className="role">{person.role}</span><h3>{person.name}</h3><p>{person.bio}</p></div></article>)}</div></section></Shell>}

export function ClubsPage(){return <Shell active="Klubet"><PageHeading section="KOMUNITETI YNË" title="Klubet e federatës" text="Nga çdo qytet, me të njëjtin pasion. Klubet që bëhen pjesë e auto sportit të Kosovës."/><section className="container section">{clubsData.isDemo && <DemoNotice/>}<SectionHeading eyebrow="KLUBET" title="Një sport që na bashkon."/><div className="clubs-grid">{clubsData.clubs.map((club,i)=><article className="club-card" key={club.id}><div className="club-card-top">{club.logo?<img className="club-logo" src={club.logo} alt={'Logo e '+club.name} loading="lazy"/>:<span className="club-placeholder"><Flag size={29} strokeWidth={1.5}/></span>}<span className="club-index">{String(i+1).padStart(2,'0')}</span></div><h3>{club.name}</h3><div className="location"><MapPin size={15}/>{club.city}</div><p>{club.description}</p><div className="chips">{club.disciplines.map(d=><span key={d}>{d}</span>)}</div>{club.website&&<a href={club.website} className="text-link" target="_blank" rel="noreferrer">Faqja e klubit <ArrowUpRight size={18}/></a>}</article>)}</div>{clubsData.clubs.length===0&&<p className="empty-state">Lista e klubeve do të publikohet së shpejti.</p>}</section></Shell>}

const months=['Janar','Shkurt','Mars','Prill','Maj','Qershor','Korrik','Gusht','Shtator','Tetor','Nëntor','Dhjetor'];
export function CalendarPage(){
 const events = [...calendarData.events].sort((a,b)=>a.startDate.localeCompare(b.startDate));
 return <Shell active="Kalendari"><PageHeading section={'KAMPIONATI I KOSOVËS / '+calendarData.year} title={'Kalendari '+calendarData.year} text="Një sezon plot adrenalinë. Datat, disiplinat dhe vendet e garave."/><section className="container section"><div className="calendar-toolbar"><div className="eyebrow"><span/>{calendarData.isComplete?'KALENDARI I GARAVE':'GARA TË KONFIRMUARA'}</div><a href="/dokumentet/" className="text-link"><Download size={17}/> Dokumentet e garave</a></div>{calendarData.note&&<div className="notice"><CalendarDays size={22}/><p>{calendarData.note}</p></div>}<a href={calendarData.poster} className="text-link poster-link" target="_blank" rel="noreferrer">Shih posterin zyrtar të kalendarit <ArrowUpRight size={18}/></a><div className="event-list">{events.map(event=>{const [year,month,day]=event.startDate.split('-'); const endDay=event.endDate.split('-')[2]; return <article className="event-row" key={event.id}><div className="event-date"><strong>{Number(day)}{day!==endDay?'–'+Number(endDay):''}</strong><span>{months[Number(month)-1]} {year}</span></div><div className="event-main"><span className="role">{event.discipline}</span><h2>{event.name}</h2><div className="location"><MapPin size={15}/>{event.location}</div>{event.organizer && <p className="event-organizer">Organizator: {event.organizer}</p>}</div><a className="text-link event-link" href={calendarData.sourceUrl} target="_blank" rel="noreferrer">Njoftimi <ArrowUpRight size={20}/></a></article>})}</div>{!events.length&&<div className="empty-state">Kalendari i këtij viti do të publikohet së shpejti.</div>}<div className="calendar-bottom"><p>Ndiqni njoftimet e federatës për çdo ndryshim të datave.</p><a className="text-link" href={calendarData.sourceUrl} target="_blank" rel="noreferrer">FASK në Facebook <ArrowUpRight size={18}/></a></div></section></Shell>
}

type DocumentEntry={file:string;title:string;category:string;sourceUrl:string;url:string;size:number};
const documents = documentData as DocumentEntry[];
function fileSize(bytes:number){return bytes>=1048576?(bytes/1048576).toFixed(1)+' MB':Math.max(1,Math.ceil(bytes/1024))+' KB'}
export function DocumentsPage(){
 const [selected,setSelected]=useState(documents[0]?.file ?? '');
 const doc=documents.find(d=>d.file===selected);
 return <Shell active="Dokumentet"><PageHeading section="BIBLIOTEKA E FEDERATËS" title="Dokumentet" text="Rregulloret, kalendari dhe dokumentet e publikuara të federatës, në një vend."/><section className="container section documents-layout"><div className="document-panel"><div className="document-icon"><FileText size={34}/></div><h2>Zgjidhni dokumentin.</h2><p className="muted">Përzgjidhni një dokument nga lista për ta hapur ose shkarkuar në formatin PDF.</p><label htmlFor="document-select">Dokumenti</label><NativeSelect id="document-select" className="document-select" value={selected} onChange={e=>setSelected(e.target.value)} disabled={!documents.length}><NativeSelectOption value="">{documents.length?'Zgjidhni një dokument…':'Nuk ka dokumente të publikuara'}</NativeSelectOption>{documents.map(d=><NativeSelectOption key={d.file} value={d.file}>{d.title}</NativeSelectOption>)}</NativeSelect><div className="document-selection" aria-live="polite">{doc?<><span className="role">{doc.category}</span><h3>{doc.title}</h3><span className="file-meta">PDF · {fileSize(doc.size)}</span><div className="document-actions"><a className="button yellow-button" href={doc.url} download={doc.file.split('/').at(-1)}>Shkarko PDF <Download size={18}/></a><a className="text-link" href={doc.url} target="_blank" rel="noreferrer">Hap dokumentin <ArrowUpRight size={18}/></a></div>{doc.sourceUrl&&<a className="source-link" href={doc.sourceUrl} target="_blank" rel="noreferrer">Burimi i dokumentit ↗</a>}</>:<div className="selection-hint"><Download size={20}/><span>{documents.length?'Dokumenti i zgjedhur do të shfaqet këtu.':'Dokumentet do të publikohen së shpejti.'}</span></div>}</div></div><aside className="documents-aside"><span className="eyebrow">NË DISPOZICION</span><strong>{String(documents.length).padStart(2,'0')}</strong><span>dokumente PDF</span><div className="aside-divider"/><h3>Përgatituni për garën.</h3><p>Kontrolloni rregulloren përkatëse dhe njoftimet e fundit para çdo pjesëmarrjeje.</p><a href="/kalendari/" className="text-link">Shih kalendarin <ArrowUpRight size={18}/></a></aside></section></Shell>
}

export function NewsPage(){return <Shell active="Lajmet"><PageHeading section="NJOFTIME · REZULTATE · AKTIVITETE" title="Lajmet e federatës" text="Qëndroni pranë garës. Publikimet nga faqja e FASK-ut në Facebook."/><section className="container section news-layout"><div className="news-intro"><div className="eyebrow"><span/> NGA FAQJA E FASK-UT</div><h2>Çdo garë.<br/>Çdo moment.</h2><p>Njoftimet e reja të federatës shfaqen këtu përmes faqes sonë në Facebook.</p><a className="button yellow-button" href={FACEBOOK} target="_blank" rel="noreferrer">Na ndiqni <ArrowUpRight size={19}/></a><figure><img src="/images/racing.jpg" alt="Starti i garës Drag Race në Kosovë" loading="lazy"/><figcaption>Foto: Shpend Ahmeti / <a href="https://autoportali.com/drag-race-2-tubon-garuesit-tane-dhe-ata-te-rajonit/" target="_blank" rel="noreferrer">Autoportali</a></figcaption></figure><a href="/kalendari/" className="news-calendar"><CalendarDays size={25}/><div><span>SEZONI 2026</span><h3>Shihemi në pistë.</h3></div><ArrowUpRight size={23}/></a></div><FacebookFeed/></section></Shell>}
