'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, CalendarDays, Flag, Menu, X, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
export const FACEBOOK = 'https://www.facebook.com/FASKKOSOVA';
const navigation = [['/', 'Ballina'], ['/bordi', 'Bordi'], ['/klubet', 'Klubet'], ['/kalendari', 'Kalendari'], ['/dokumentet', 'Dokumentet'], ['/lajmet', 'Lajmet']];
export function Shell({ active, children }: { active: string; children: React.ReactNode }) {
 const [menuOpen, setMenuOpen] = useState(false);
 return <><a href="#permbajtja" className="skip-link">Kalo te përmbajtja</a>
 <div className="topbar"><div className="container"><span>FEDERATA E AUTO SPORTIT E KOSOVËS</span><a href={FACEBOOK} target="_blank" rel="noreferrer">Na ndiqni në Facebook <ArrowUpRight size={13}/></a></div></div>
 <header className="header"><div className="container header-inner"><Link href="/" className="brand" aria-label="FASK — Ballina"><span className="brand-word">FASK<span className="brand-slash">/</span></span><span className="brand-description">FEDERATA E AUTO SPORTIT<br/>E KOSOVËS</span></Link>
 <nav className={menuOpen ? 'nav open' : 'nav'} aria-label="Navigimi kryesor">{navigation.map(([href,label]) => <Link key={href} href={href} aria-current={active === label ? 'page' : undefined} onClick={()=>setMenuOpen(false)}>{label}</Link>)}</nav>
 <span className="language">SQ <span> / KOS</span></span><Button className="menu-button" variant="ghost" aria-label={menuOpen ? 'Mbyll menynë' : 'Hap menynë'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</Button></div></header>
 <main id="permbajtja">{children}</main><footer><div className="container footer-main"><div><Link href="/" className="footer-brand">FASK<span>/</span></Link><p>Federata e Auto Sportit e Kosovës</p><span className="muted">Pasioni ynë. Sporti ynë. Kosova jonë.</span></div><div><h3>Federata</h3><Link href="/bordi">Bordi i federatës</Link><Link href="/klubet">Klubet</Link><Link href="/lajmet">Lajmet</Link></div><div><h3>Për garuesit</h3><Link href="/kalendari">Kalendari i garave</Link><Link href="/dokumentet">Dokumentet</Link></div><div><h3>Na kontaktoni</h3><a href="mailto:info@fask-ks.org">info@fask-ks.org <ArrowUpRight size={14}/></a><span>Prishtinë, Kosovë</span><a href={FACEBOOK} target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} FASK. Të gjitha të drejtat e rezervuara.</span><span>AUTO SPORTI NA BASHKON.</span></div></footer></>;
}
export function PageHeading({section, title, text}: {section:string;title:string;text:string}) {
 return <div className="page-heading"><div className="container"><div className="eyebrow"><span/> {section}</div><h1>{title}<span className="yellow">.</span></h1><p>{text}</p></div></div>;
}
export function SectionHeading({eyebrow,title,href,label}: {eyebrow:string;title:string;href?:string;label?:string}) {
 return <div className="section-heading"><div><div className="eyebrow"><span/>{eyebrow}</div><h2>{title}</h2></div>{href && <Link href={href} className="text-link">{label} <ArrowUpRight size={19}/></Link>}</div>;
}
export function HomePage() {
 return <Shell active="Ballina"><section className="hero"><img src="/images/hero.jpg" alt="Veturë garuese në një kthesë të garës malore në Kosovë" className="hero-image" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><div className="eyebrow"><span/> PASION. PËRKUSHTIM. GARË.</div><h1>NJË PASION.<br/>NJË <span>KOMB.</span><br/>PA KUFIJ.</h1><p>Shtëpia e auto sportit në Kosovë.<br/>Bashkë në çdo kthesë, drejt çdo fitoreje.</p><div className="hero-actions"><Link href="/kalendari" className="button yellow-button">Kalendari 2026 <ArrowUpRight size={19}/></Link><Link href="/lajmet" className="hero-news">Lajmet e federatës <ArrowRight size={19}/></Link></div></div><div className="hero-caption"><span>KAMPIONATI I KOSOVËS</span><strong>Çdo sekondë ka rëndësi.</strong></div><div className="hero-bottom"><span>01 — AUTO SPORTI I KOSOVËS</span><span>FASK / 2026</span></div></section>
 <div className="discipline-strip"><div className="container"><Flag size={21}/>{['GARA MALORE','AUTO SLLALLOM','DRAG RACE','KARTING','DRIFT','E-SPORT'].map(x=><span key={x}>{x}</span>)}</div></div>
 <section className="container home-news section"><SectionHeading eyebrow="NGA FEDERATA" title="Në ritmin e garës." href="/lajmet" label="Të gjitha lajmet"/><div className="home-grid"><Link href="/lajmet" className="feature-story"><img src="/images/racing.jpg" alt="Garuesit dhe publiku në startin e një gare Drag Race në Kosovë" loading="lazy"/><div className="feature-shade"/><div className="feature-story-copy"><span className="tag">FASK NË FACEBOOK</span><h3>Nga pista, drejtpërdrejt<br/>te ju.</h3><p>Njoftimet, rezultatet dhe momentet e fundit të federatës.</p><span className="circle-arrow"><ArrowUpRight/></span></div></Link><div className="home-side"><div className="season-card"><div className="eyebrow">SEZONI 2026 <CalendarDays size={20}/></div><span className="season-number">2026<span>↗</span></span><h3>Takimi ynë është në pistë.</h3><p>Shihni datat dhe vendet e garave të publikuara për këtë sezon.</p><Link href="/kalendari" className="text-link">Eksploro kalendarin <ArrowRight size={18}/></Link></div><Link href="/dokumentet" className="download-card"><FileText size={30}/><div><span>PËR GARUESIT DHE KLUBET</span><h3>Dokumentet e federatës</h3></div><ArrowUpRight/></Link></div></div></section>
 <section className="federation-section"><div className="container federation-grid"><div><div className="eyebrow"><span/> NJË KOMUNITET. NJË QËLLIM.</div><h2>Më shumë<br/>se një garë.</h2></div><div><p>Klubet, garuesit dhe njerëzit që e çojnë përpara auto sportin e Kosovës. Njihuni me federatën dhe komunitetin tonë.</p><div className="federation-links"><Link href="/bordi">Bordi i federatës <ArrowUpRight/></Link><Link href="/klubet">Klubet tona <ArrowUpRight/></Link></div></div></div></section>
 </Shell>;
}
